"""empty message

Revision ID: 1ca6c9ea0f76
Revises: 
Create Date: 2020-04-12 15:08:03.712750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca6c9ea0f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=256), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_created'), 'game', ['created'], unique=False)
    op.create_index(op.f('ix_game_game_id'), 'game', ['game_id'], unique=True)
    op.create_table('hat_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('picked', sa.Boolean(), nullable=True),
    sa.Column('submitter', sa.String(length=256), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hat_pick_timestamp'), 'hat_pick', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hat_pick_timestamp'), table_name='hat_pick')
    op.drop_table('hat_pick')
    op.drop_index(op.f('ix_game_game_id'), table_name='game')
    op.drop_index(op.f('ix_game_created'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
